apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-svc
spec:
  selector:
    app: ws
  ports:
    - port: 8080
      targetPort: 80