apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap 
  namespace: {{ .Values.namespace }}
data:
  PG_HOST: "{{ .Release.Name }}-pg-service"
  PG_PORT: "{{ .Values.app.postgres.port }}"
  PG_DATABASE: "{{ .Values.app.postgres.database }}"
