apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pg-service
  namespace:  {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
  type: ClusterIP
