apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod-1
  labels:
    team: back
spec:
  containers:
  - name: ws
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: team
                operator: In
                values:
                  - back
          topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod-2
  labels:
    team: back
spec:
  containers:
  - name: ws
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: team
                operator: In
                values:
                  - back
          topologyKey: "kubernetes.io/hostname"