apiVersion: v1
kind: Pod
metadata:
  name: resourced-pod
  labels:
    app: resources
spec:
  containers:
    - name: ws
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: pod-svc
spec:
  selector:
    app: resources
  ports:
    - port: 80
      targetPort: 80