apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-job
  namespace: jobs-demo
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: python:3.11-alpine
        command: ["python", "-c", "print('db migration demo job completed')"]
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-service:5432/postgres"
      restartPolicy: Never
  backoffLimit: 3
