namespace: metrics-app
app:
  replicaCount: 2
  image:
    repository: nginx
    tag: stable-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  postgres:
    host: postgres
    port: 5432
    database: "metrics-app"

postgresql:
  enabled: true
  database: "metrics-app"
  service:
    type: ClusterIP
    port: 5432
